# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEZOrMSQa04zpIonNpHwOOYg2uAZ6NDi
"""

!pip install transformers torch --quiet

import pandas as pd
import re
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, random_split
from transformers import BertTokenizer, BertModel
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

import os
from pathlib import Path
import pandas as pd

# 1. List files in the root /content folder
print("Files in /content:")
print(os.listdir('/content'))

# 2. Search recursively for any CSV under /content
csv_files = list(Path('/content').rglob('*.csv'))
print("\nCSV files found:")
for path in csv_files:
    print(" ", path)

# 3. Load the dataset (adjust the path to whichever CSV you see)
dataset_path = '/content/cleaned_twitter_data.csv'  # or the full path you discovered
df_full = pd.read_csv(dataset_path)

# 4. Verify load
print("\nTotal tweets:", len(df_full))
print(df_full.columns)
print(df_full.head())

import re

# Define the cleaning function
def clean_tweet(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)   # remove URLs
    text = re.sub(r"@\w+", "", text)             # remove mentions
    text = re.sub(r"#\w+", "", text)             # remove hashtags
    text = re.sub(r"[^\w\s]", "", text)          # remove punctuation
    return text.strip()

# Apply to your DataFrame
df_full['Cleaned_Tweet'] = df_full['Tweet_text'].astype(str).apply(clean_tweet)

# Verify it worked
print(df_full[['Tweet_text','Cleaned_Tweet']].head())

from transformers import DistilBertTokenizer, DistilBertModel
import torch
import numpy as np
from tqdm.auto import tqdm

# 1. Load tokenizer & model on GPU
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model_distil = DistilBertModel.from_pretrained('distilbert-base-uncased') \
                              .eval().to('cuda')

# 2. Prepare text input
texts = df_full['Cleaned_Tweet'].astype(str).tolist()

# 3. Set a safe batch size for Google Colab
batch_size = 16
embeddings = []

# 4. Encode in batches and collect [CLS] embeddings
n_batches = (len(texts) + batch_size - 1) // batch_size
for i in tqdm(range(0, len(texts), batch_size), total=n_batches):
    batch = texts[i : i + batch_size]

    encodings = tokenizer(
        batch,
        padding='max_length',
        truncation=True,
        max_length=128,
        return_tensors='pt'
    )

    input_ids = encodings['input_ids'].to('cuda')
    attention_mask = encodings['attention_mask'].to('cuda')

    with torch.no_grad():
        outputs = model_distil(input_ids, attention_mask=attention_mask)

    # Extract CLS token embedding
    cls_embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()
    embeddings.append(cls_embeddings)

    # Optional: clear GPU cache
    torch.cuda.empty_cache()

# 5. Combine all CLS embeddings into one array
bert_features_full = np.vstack(embeddings)

# 6. Print the shape
print("✅ DistilBERT features shape:", bert_features_full.shape)

# 7. Optional: save features to disk
np.save("bert_features_full.npy", bert_features_full)

import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. Select relevant behavioral features
behavior_cols = [
    'Word_Count', 'Url_Count', 'Retweet', 'Mentions_Count', 'Hashtags_Count',
    'Followers', 'Following'
]

# 2. Handle any missing values (if needed)
df_full[behavior_cols] = df_full[behavior_cols].fillna(0)

# 3. Extract and scale behavioral features
X_behav = df_full[behavior_cols].astype(float).values
scaler = StandardScaler()
X_behav_scaled = scaler.fit_transform(X_behav)

print("✅ Behavioral features shape:", X_behav_scaled.shape)

import torch
from torch.utils.data import Dataset, DataLoader, random_split

# 1. Convert to torch tensors
X_text_tensor  = torch.tensor(bert_features_full, dtype=torch.float32)
X_behav_tensor = torch.tensor(X_behav_scaled, dtype=torch.float32)
y_tensor       = torch.tensor(df_full['Label'].values, dtype=torch.float32)

# 2. Custom Dataset
class FullHybridDataset(Dataset):
    def __init__(self, x_text, x_behav, y):
        self.x_text = x_text
        self.x_behav = x_behav
        self.y = y
    def __len__(self):
        return len(self.y)
    def __getitem__(self, idx):
        return self.x_text[idx], self.x_behav[idx], self.y[idx]

dataset = FullHybridDataset(X_text_tensor, X_behav_tensor, y_tensor)

# 3. Split
train_size = int(0.8 * len(dataset))
val_size   = len(dataset) - train_size
train_ds, val_ds = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_ds, batch_size=128, shuffle=True)
val_loader   = DataLoader(val_ds, batch_size=128)

import torch.nn as nn

class HybridModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.text_branch = nn.Sequential(
            nn.Linear(768, 256),
            nn.ReLU(),
            nn.Dropout(0.3)
        )
        self.behav_branch = nn.Sequential(
            nn.Linear(7, 16),
            nn.ReLU(),
            nn.Dropout(0.3)
        )
        self.classifier = nn.Sequential(
            nn.Linear(256 + 16, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x_text, x_behav):
        t = self.text_branch(x_text)
        b = self.behav_branch(x_behav)
        combined = torch.cat((t, b), dim=1)
        return self.classifier(combined)

model = HybridModel().to('cuda')
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

for epoch in range(5):
    model.train()
    total_loss = 0
    for xt, xb, yb in train_loader:
        xt, xb, yb = xt.to('cuda'), xb.to('cuda'), yb.to('cuda').unsqueeze(1)
        optimizer.zero_grad()
        preds = model(xt, xb)
        loss = loss_fn(preds, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}/5 - Loss: {total_loss/len(train_loader):.4f}")

from sklearn.metrics import classification_report

model.eval()
all_preds, all_labels = [], []

with torch.no_grad():
    for xt, xb, yb in val_loader:
        xt, xb = xt.to('cuda'), xb.to('cuda')
        preds = model(xt, xb)
        preds = (preds.cpu().numpy() > 0.5).astype(int)
        all_preds.extend(preds.flatten())
        all_labels.extend(yb.numpy().flatten())

print(" Validation Accuracy Report:\n")
print(classification_report(all_labels, all_preds, digits=4))

from transformers import DistilBertModel

class HybridModelFineTune(torch.nn.Module):
    def __init__(self, dropout=0.3):
        super().__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.text_branch = torch.nn.Sequential(
            torch.nn.Linear(768, 256),
            torch.nn.ReLU(),
            torch.nn.Dropout(dropout)
        )
        self.behavior_branch = torch.nn.Sequential(
            torch.nn.Linear(7, 32),
            torch.nn.ReLU(),
            torch.nn.Dropout(dropout)
        )
        self.classifier = torch.nn.Sequential(
            torch.nn.Linear(256 + 32, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, 1)
        )

    def forward(self, x_text, x_behav, attention_mask=None):
        cls_output = self.bert(x_text, attention_mask=attention_mask).last_hidden_state[:, 0]
        t = self.text_branch(cls_output)
        b = self.behavior_branch(x_behav)
        combined = torch.cat((t, b), dim=1)
        return self.classifier(combined)

# ------------------- STEP 1: Upload & Load Dataset -------------------
import pandas as pd
from google.colab import files

uploaded = files.upload()  # Upload cleaned_twitter_data.csv

# Replace with actual uploaded filename if different
df_full = pd.read_csv("cleaned_twitter_data.csv")
df_full.head()

import os
from pathlib import Path
import pandas as pd

# 1. List files in the root /content folder
print("Files in /content:")
print(os.listdir('/content'))

# 2. Search recursively for any CSV under /content
csv_files = list(Path('/content').rglob('*.csv'))
print("\nCSV files found:")
for path in csv_files:
    print(" ", path)

# 3. Load the dataset (adjust the path to whichever CSV you see)
dataset_path = '/content/cleaned_twitter_data.csv'
df_full = pd.read_csv(dataset_path)

# 4. Verify load
print("\nTotal tweets:", len(df_full))
print(df_full.columns)
print(df_full.head())

import re

# Define the cleaning function
def clean_tweet(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)   # remove URLs
    text = re.sub(r"@\w+", "", text)             # remove mentions
    text = re.sub(r"#\w+", "", text)             # remove hashtags
    text = re.sub(r"[^\w\s]", "", text)          # remove punctuation
    return text.strip()

# Apply to your DataFrame
df_full['Cleaned_Tweet'] = df_full['Tweet_text'].astype(str).apply(clean_tweet)

# Verify it worked
print(df_full[['Tweet_text','Cleaned_Tweet']].head())

# ------------------- STEP 2: Tokenize Tweets using DistilBERT -------------------
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

texts = df_full['Cleaned_Tweet'].astype(str).tolist()

# Tokenize all tweets in one go
encodings = tokenizer(
    texts,
    padding='max_length',
    truncation=True,
    max_length=128,
    return_tensors='pt'
)

input_ids      = encodings['input_ids']
attention_mask = encodings['attention_mask']

import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from transformers import DistilBertTokenizer, DistilBertModel
from torch.optim import AdamW
from torch.utils.data import TensorDataset, DataLoader


# Normalize behavioral features (optional but recommended)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
behavior_features = scaler.fit_transform(behavior_features)

# === 2. Tokenize Text ===
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

input_ids = encodings['input_ids']
attention_mask = encodings['attention_mask']
behavior_tensor = torch.tensor(behavior_features).float()
labels_tensor = torch.tensor(labels).float()

# === 3. Train/Test Split ===
train_idx, val_idx = train_test_split(range(len(labels)), test_size=0.2, random_state=42)

train_dataset = TensorDataset(
    input_ids[train_idx], attention_mask[train_idx],
    behavior_tensor[train_idx], labels_tensor[train_idx]
)
val_dataset = TensorDataset(
    input_ids[val_idx], attention_mask[val_idx],
    behavior_tensor[val_idx], labels_tensor[val_idx]
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

# === 4. Hybrid Model Definition ===
class HybridModel(nn.Module):
    def __init__(self, behavior_dim):
        super(HybridModel, self).__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.behavior_branch = nn.Sequential(
            nn.Linear(behavior_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 16)
        )
        self.classifier = nn.Linear(768 + 16, 1)  # 768 from DistilBERT + 16 from behavior

    def forward(self, input_ids, attention_mask, behavior_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = self.dropout(bert_output.last_hidden_state[:, 0, :])  # CLS token
        behavior_output = self.behavior_branch(behavior_features)
        combined = torch.cat((cls_output, behavior_output), dim=1)
        logits = self.classifier(combined)
        return logits

# === 5. Training Setup ===
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridModel(behavior_dim=behavior_tensor.shape[1]).to(device)

criterion = nn.BCEWithLogitsLoss()
optimizer = AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)

best_val_acc = 0.0

# === 6. Training Loop ===
for epoch in range(7):  # ← you can increase/decrease
    model.train()
    total_loss = 0

    for batch in train_loader:
        ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
        optimizer.zero_grad()
        outputs = model(ids, masks, behaviors).squeeze()
        loss = criterion(outputs, labels_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} - Training Loss: {avg_train_loss:.4f}")

    # === Validation ===
    model.eval()
    preds, true_labels = [], []

    with torch.no_grad():
        for batch in val_loader:
            ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
            outputs = model(ids, masks, behaviors).squeeze()
            preds.extend(torch.round(torch.sigmoid(outputs)).cpu().numpy())
            true_labels.extend(labels_batch.cpu().numpy())

    print("\n Validation Accuracy Report:\n")
    print(classification_report(true_labels, preds, digits=4))

    # Save best model
    from sklearn.metrics import accuracy_score
    val_acc = accuracy_score(true_labels, preds)
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_hybrid_model.pt")
        print("Best model saved!\n")

print(" Training complete.")

from google.colab import files
# Click and select cleaned_twitter_data.csv (and best_hybrid_model.pt if you have it)
uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

import pandas as pd, os
csv_path = 'cleaned_twitter_data.csv'
assert os.path.exists(csv_path), f"{csv_path} not found — upload it first."

df = pd.read_csv(csv_path)
print("Rows:", len(df))
print("Columns:", df.columns.tolist())
display(df.head(3))

# === Prepare variables used in training code ===
TEXT_COL  = 'Tweet_text'
LABEL_COL = 'Label'
beh_cols  = ['Word_Count','Url_Count','Retweet','Mentions_Count','Hashtags_Count','Followers','Following']

# check columns
missing = [c for c in [TEXT_COL, LABEL_COL] + beh_cols if c not in df.columns]
if missing:
    raise KeyError(f"Missing columns in CSV: {missing}. Edit TEXT_COL / beh_cols to match df.columns() output from previous cell.")

# Build arrays / lists
texts = df[TEXT_COL].astype(str).tolist()
# Convert label values to 0/1 integers (handles strings like 'phish' or '1')
def map_label(x):
    xs = str(x).strip().lower()
    if xs in ['1','true','yes','phish','phishing','malicious']: return 1
    if xs in ['0','false','no','benign','legit','legitimate']: return 0
    try:
        return int(float(xs))
    except:
        return 1 if xs not in ['', 'nan', 'none'] else 0

labels = [map_label(v) for v in df[LABEL_COL].tolist()]

import numpy as np
behavior_features = df[beh_cols].fillna(0).values.astype(float)  # shape (N,7)
print("Prepared: texts len", len(texts), "labels len", len(labels), "behavior_features shape", behavior_features.shape)

from sklearn.preprocessing import MinMaxScaler
import joblib

scaler = MinMaxScaler()
behavior_features = scaler.fit_transform(behavior_features)
# Save a copy of scaler for inference later
joblib.dump(scaler, 'scaler_demo.save')
print("Scaled behavior_features and saved scaler_demo.save")

from transformers import DistilBertTokenizer
import torch

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

input_ids = encodings['input_ids']
attention_mask = encodings['attention_mask']
behavior_tensor = torch.tensor(behavior_features).float()
labels_tensor = torch.tensor(labels).float()

print("Tokenization complete. input_ids shape:", input_ids.shape, "behavior_tensor shape:", behavior_tensor.shape, "labels_tensor shape:", labels_tensor.shape)

from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

train_idx, val_idx = train_test_split(range(len(labels)), test_size=0.2, random_state=42)

train_dataset = TensorDataset(
    input_ids[train_idx], attention_mask[train_idx],
    behavior_tensor[train_idx], labels_tensor[train_idx]
)
val_dataset = TensorDataset(
    input_ids[val_idx], attention_mask[val_idx],
    behavior_tensor[val_idx], labels_tensor[val_idx]
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)
print("Loaders ready. Train batches:", len(train_loader), "Val batches:", len(val_loader))

# ------- Fix cell: re-import, recover behavior tensor, define + instantiate model -------

# 0. (Optional) install transformers if not present — uncomment if import fails
# !pip install -q transformers

# 1. imports
import os
import torch
import torch.nn as nn
from transformers import DistilBertModel, DistilBertTokenizer

print("torch:", torch.__version__, "cuda:", torch.cuda.is_available())

# 2. Ensure tokenizer available (will download if needed)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# 3. Recover behavior_tensor or rebuild it from known variables if kernel was reset
# The training flow used variables named 'behavior_tensor' and 'behavior_features' and a dataframe 'df' with beh_cols.
# Attempt to use an existing behavior_tensor; otherwise build from behavior_features or df.

behavior_tensor_exists = 'behavior_tensor' in globals()
behavior_features_exists = 'behavior_features' in globals()
df_exists = 'df' in globals()
beh_cols_exists = 'beh_cols' in globals()

print("behavior_tensor in globals():", behavior_tensor_exists)
print("behavior_features in globals():", behavior_features_exists)
print("df in globals():", df_exists)
print("beh_cols in globals():", beh_cols_exists)

if not behavior_tensor_exists:
    if behavior_features_exists:
        # convert numpy array -> torch tensor
        try:
            behavior_tensor = torch.tensor(behavior_features, dtype=torch.float32)
            print("Rebuilt behavior_tensor from behavior_features with shape", behavior_tensor.shape)
        except Exception as e:
            print("Could not build behavior_tensor from behavior_features:", e)
    elif df_exists and beh_cols_exists:
        # build from df and beh_cols (most robust fallback)
        import numpy as np
        try:
            arr = df[beh_cols].fillna(0).values.astype(float)
            behavior_tensor = torch.tensor(arr, dtype=torch.float32)
            print("Built behavior_tensor from df[beh_cols] with shape", behavior_tensor.shape)
        except Exception as e:
            print("Failed to build behavior_tensor from df and beh_cols:", e)
    else:
        raise RuntimeError(
            "No behavior tensor/array found. Re-run the preprocessing cell that creates 'behavior_features' or ensure 'df' and 'beh_cols' are defined."
        )
else:
    print("Using existing behavior_tensor with shape", behavior_tensor.shape)

# 4. Determine behavior_dim for model instantiation
behavior_dim = behavior_tensor.shape[1] if hasattr(behavior_tensor, 'shape') else None
if behavior_dim is None:
    raise RuntimeError("Could not determine behavior_dim. Make sure behavior_tensor has shape (N, D).")
print("behavior_dim =", behavior_dim)

# 5. Define HybridModel (same architecture used before)
class HybridModel(nn.Module):
    def __init__(self, behavior_dim):
        super(HybridModel, self).__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.behavior_branch = nn.Sequential(
            nn.Linear(behavior_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 16)
        )
        self.classifier = nn.Linear(768 + 16, 1)

    def forward(self, input_ids, attention_mask, behavior_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = self.dropout(bert_output.last_hidden_state[:, 0, :])
        behavior_output = self.behavior_branch(behavior_features)
        combined = torch.cat((cls_output, behavior_output), dim=1)
        logits = self.classifier(combined)
        return logits

# 6. Instantiate model on device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridModel(behavior_dim=behavior_dim).to(device)
print("Model instantiated on", device)

# 7. If you have a saved checkpoint in working dir, load it now
ckpt = "best_hybrid_model.pt"
if os.path.exists(ckpt):
    try:
        state = torch.load(ckpt, map_location=device)
        model.load_state_dict(state)
        print("Loaded state_dict from", ckpt)
    except Exception as e:
        print("Could not load state_dict directly:", e)
        try:
            # try loading as a full model object
            model = torch.load(ckpt, map_location=device)
            print("Loaded full model object from", ckpt)
        except Exception as e2:
            print("Second load attempt failed:", e2)
else:
    print(f"No checkpoint found at '{ckpt}' in working dir. If you want predictions, upload the file now.")

# 8. Set model to eval mode
model.eval()

import torch.nn as nn

class HybridModel(nn.Module):
    def __init__(self, behavior_dim):
        super(HybridModel, self).__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.behavior_branch = nn.Sequential(
            nn.Linear(behavior_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 16)
        )
        self.classifier = nn.Linear(768 + 16, 1)

    def forward(self, input_ids, attention_mask, behavior_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = self.dropout(bert_output.last_hidden_state[:, 0, :])
        behavior_output = self.behavior_branch(behavior_features)
        combined = torch.cat((cls_output, behavior_output), dim=1)
        logits = self.classifier(combined)
        return logits

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridModel(behavior_dim=behavior_tensor.shape[1]).to(device)
print("Model instantiated on device:", device)

from torch.optim import AdamW
import torch

criterion = nn.BCEWithLogitsLoss()
optimizer = AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)

best_val_acc = 0.0

for epoch in range(2):
    model.train()
    total_loss = 0

    for batch in train_loader:
        ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
        optimizer.zero_grad()
        outputs = model(ids, masks, behaviors).squeeze()
        loss = criterion(outputs, labels_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} - Training Loss: {avg_train_loss:.4f}")

    # Validation
    model.eval()
    preds, true_labels = [], []

    with torch.no_grad():
        for batch in val_loader:
            ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
            outputs = model(ids, masks, behaviors).squeeze()
            preds.extend(torch.round(torch.sigmoid(outputs)).cpu().numpy())
            true_labels.extend(labels_batch.cpu().numpy())

    from sklearn.metrics import classification_report, accuracy_score
    val_acc = accuracy_score(true_labels, preds)
    print("\n Validation Accuracy Report:\n")
    print(classification_report(true_labels, preds, digits=4))

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_hybrid_model.pt")
        print("Best model saved!\n")

print("Training complete. Best val acc:", best_val_acc)

import torch
import numpy as np
from tqdm.notebook import tqdm

def predict_on_texts(texts, beh_vectors, batch_size=16):
    """
    texts: list[str]
    beh_vectors: list[list[float]] (same order)
    returns: list of probabilities (floats)
    """
    probs = []
    model.to(device)
    model.eval()
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i+batch_size]
        batch_beh = beh_vectors[i:i+batch_size]
        enc = tokenizer(batch_texts, padding='max_length', truncation=True, max_length=128, return_tensors='pt')
        input_ids = enc['input_ids'].to(device)
        attention_mask = enc['attention_mask'].to(device)
        beh_scaled = scaler.transform(batch_beh)
        beh_tensor = torch.tensor(beh_scaled, dtype=torch.float32).to(device)
        with torch.no_grad():
            logits = model(input_ids, attention_mask, beh_tensor).squeeze()
            batch_probs = torch.sigmoid(logits).cpu().numpy()
        # normalize output shape
        if np.isscalar(batch_probs):
            probs.append(float(batch_probs))
        else:
            probs.extend(batch_probs.tolist())
    return probs

N = 5
sample = df.sample(n=N, random_state=42).reset_index(drop=False)  # keep original index in column 'index'
texts = sample['Tweet_text'].astype(str).tolist()
beh_cols = ['Word_Count','Url_Count','Retweet','Mentions_Count','Hashtags_Count','Followers','Following']
beh = sample[beh_cols].fillna(0).values.tolist()

probs = predict_on_texts(texts, beh, batch_size=8)
sample['pred_prob'] = probs
sample['pred_label'] = (sample['pred_prob'] > 0.5).astype(int)
# Display relevant columns neatly
display(sample[['index','Tweet_text','pred_prob','pred_label','Label']])

per_class = 3
phish = df[df['Label'].astype(int)==1].sample(n=per_class, random_state=1)
benign = df[df['Label'].astype(int)==0].sample(n=per_class, random_state=1)
balanced = pd.concat([phish, benign]).reset_index(drop=False)
texts = balanced['Tweet_text'].astype(str).tolist()
beh = balanced[beh_cols].fillna(0).values.tolist()

probs = predict_on_texts(texts, beh, batch_size=8)
balanced['pred_prob'] = probs
balanced['pred_label'] = (balanced['pred_prob'] > 0.5).astype(int)
display(balanced[['index','Tweet_text','pred_prob','pred_label','Label']])

# Load scaler (if you restarted session earlier, re-load tokenizer/model/scaler first)
import joblib, time
scaler = joblib.load('scaler_demo.save')

def predict_one(tweet_text, beh_vector, threshold=0.5):
    enc = tokenizer([tweet_text], padding='max_length', truncation=True, max_length=128, return_tensors='pt')
    input_ids = enc['input_ids'].to(device)
    attention_mask = enc['attention_mask'].to(device)
    beh_scaled = scaler.transform([beh_vector])
    beh_tensor = torch.tensor(beh_scaled, dtype=torch.float32).to(device)
    with torch.no_grad():
        logits = model(input_ids, attention_mask, beh_tensor).squeeze()
        prob = torch.sigmoid(logits).item()
    return prob

# Examples (adjust behavioral vectors to realistic values)
examples = [
    ("Verify your account immediately at http://bit.ly/fake", [10,1,0,0,0,1,2]),
    ("Had a great day today with friends #weekend", [8,0,1,0,1,520,400])
]
for text, beh in examples:
    t0 = time.time()
    p = predict_one(text, beh)
    t1 = time.time()
    print(f"Text: {text}\nProb(phish)={p:.4f}, Pred={(1 if p>0.5 else 0)}, latency={(t1-t0)*1000:.1f} ms\n")

# For speed, evaluate on a sample or your validation split
eval_df = df.sample(n=2000, random_state=2)   # or use your val split if available
texts = eval_df['Tweet_text'].astype(str).tolist()
beh = eval_df[beh_cols].fillna(0).values.tolist()

probs = predict_on_texts(texts, beh, batch_size=16)
eval_df = eval_df.reset_index(drop=False)
eval_df['pred_prob'] = probs
topk = eval_df.sort_values('pred_prob', ascending=False).head(10)
display(topk[['index','Tweet_text','pred_prob','Label']])

from google.colab import files
# Click and select cleaned_twitter_data.csv (and best_hybrid_model.pt if you have it)
uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

from google.colab import files
# Click and select cleaned_twitter_data.csv (and best_hybrid_model.pt if you have it)
uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

import pandas as pd
import os

csv_path = 'merged_twitter_with_synthetic.csv'   # Updated file name
assert os.path.exists(csv_path), f"{csv_path} not found — upload it first."

df = pd.read_csv(csv_path)
print("Rows:", len(df))
print("Columns:", df.columns.tolist())
display(df.head(3))

# === Prepare variables used in training code ===
TEXT_COL  = 'Tweet_text'
LABEL_COL = 'Label'
beh_cols  = ['Word_Count','Url_Count','Retweet','Mentions_Count','Hashtags_Count','Followers','Following']

# check columns
missing = [c for c in [TEXT_COL, LABEL_COL] + beh_cols if c not in df.columns]
if missing:
    raise KeyError(f"Missing columns in CSV: {missing}. Edit TEXT_COL / beh_cols to match df.columns() output from previous cell.")

# Build arrays / lists
texts = df[TEXT_COL].astype(str).tolist()
# Convert label values to 0/1 integers (handles strings like 'phish' or '1')
def map_label(x):
    xs = str(x).strip().lower()
    if xs in ['1','true','yes','phish','phishing','malicious']: return 1
    if xs in ['0','false','no','benign','legit','legitimate']: return 0
    try:
        return int(float(xs))
    except:
        return 1 if xs not in ['', 'nan', 'none'] else 0

labels = [map_label(v) for v in df[LABEL_COL].tolist()]

import numpy as np
behavior_features = df[beh_cols].fillna(0).values.astype(float)  # shape (N,7)
print("Prepared: texts len", len(texts), "labels len", len(labels), "behavior_features shape", behavior_features.shape)

from sklearn.preprocessing import MinMaxScaler
import joblib

scaler = MinMaxScaler()
behavior_features = scaler.fit_transform(behavior_features)
# Save a copy of scaler for inference later
joblib.dump(scaler, 'scaler_demo.save')
print("Scaled behavior_features and saved scaler_demo.save")

from transformers import DistilBertTokenizer
import torch

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

input_ids = encodings['input_ids']
attention_mask = encodings['attention_mask']
behavior_tensor = torch.tensor(behavior_features).float()
labels_tensor = torch.tensor(labels).float()

print("Tokenization complete. input_ids shape:", input_ids.shape, "behavior_tensor shape:", behavior_tensor.shape, "labels_tensor shape:", labels_tensor.shape)

from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

train_idx, val_idx = train_test_split(range(len(labels)), test_size=0.2, random_state=42)

train_dataset = TensorDataset(
    input_ids[train_idx], attention_mask[train_idx],
    behavior_tensor[train_idx], labels_tensor[train_idx]
)
val_dataset = TensorDataset(
    input_ids[val_idx], attention_mask[val_idx],
    behavior_tensor[val_idx], labels_tensor[val_idx]
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)
print("Loaders ready. Train batches:", len(train_loader), "Val batches:", len(val_loader))

# ------- Fix cell: re-import, recover behavior tensor, define + instantiate model -------

# 0. (Optional) install transformers if not present — uncomment if import fails
# !pip install -q transformers

# 1. imports
import os
import torch
import torch.nn as nn
from transformers import DistilBertModel, DistilBertTokenizer

print("torch:", torch.__version__, "cuda:", torch.cuda.is_available())

# 2. Ensure tokenizer available (will download if needed)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# 3. Recover behavior_tensor or rebuild it from known variables if kernel was reset
# The training flow used variables named 'behavior_tensor' and 'behavior_features' and a dataframe 'df' with beh_cols.
# Attempt to use an existing behavior_tensor; otherwise build from behavior_features or df.

behavior_tensor_exists = 'behavior_tensor' in globals()
behavior_features_exists = 'behavior_features' in globals()
df_exists = 'df' in globals()
beh_cols_exists = 'beh_cols' in globals()

print("behavior_tensor in globals():", behavior_tensor_exists)
print("behavior_features in globals():", behavior_features_exists)
print("df in globals():", df_exists)
print("beh_cols in globals():", beh_cols_exists)

if not behavior_tensor_exists:
    if behavior_features_exists:
        # convert numpy array -> torch tensor
        try:
            behavior_tensor = torch.tensor(behavior_features, dtype=torch.float32)
            print("Rebuilt behavior_tensor from behavior_features with shape", behavior_tensor.shape)
        except Exception as e:
            print("Could not build behavior_tensor from behavior_features:", e)
    elif df_exists and beh_cols_exists:
        # build from df and beh_cols (most robust fallback)
        import numpy as np
        try:
            arr = df[beh_cols].fillna(0).values.astype(float)
            behavior_tensor = torch.tensor(arr, dtype=torch.float32)
            print("Built behavior_tensor from df[beh_cols] with shape", behavior_tensor.shape)
        except Exception as e:
            print("Failed to build behavior_tensor from df and beh_cols:", e)
    else:
        raise RuntimeError(
            "No behavior tensor/array found. Re-run the preprocessing cell that creates 'behavior_features' or ensure 'df' and 'beh_cols' are defined."
        )
else:
    print("Using existing behavior_tensor with shape", behavior_tensor.shape)

# 4. Determine behavior_dim for model instantiation
behavior_dim = behavior_tensor.shape[1] if hasattr(behavior_tensor, 'shape') else None
if behavior_dim is None:
    raise RuntimeError("Could not determine behavior_dim. Make sure behavior_tensor has shape (N, D).")
print("behavior_dim =", behavior_dim)

# 5. Define HybridModel (same architecture used before)
class HybridModel(nn.Module):
    def __init__(self, behavior_dim):
        super(HybridModel, self).__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.behavior_branch = nn.Sequential(
            nn.Linear(behavior_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 16)
        )
        self.classifier = nn.Linear(768 + 16, 1)

    def forward(self, input_ids, attention_mask, behavior_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = self.dropout(bert_output.last_hidden_state[:, 0, :])
        behavior_output = self.behavior_branch(behavior_features)
        combined = torch.cat((cls_output, behavior_output), dim=1)
        logits = self.classifier(combined)
        return logits

# 6. Instantiate model on device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridModel(behavior_dim=behavior_dim).to(device)
print("Model instantiated on", device)

# 7. If you have a saved checkpoint in working dir, load it now
ckpt = "best_hybrid_model.pt"
if os.path.exists(ckpt):
    try:
        state = torch.load(ckpt, map_location=device)
        model.load_state_dict(state)
        print("Loaded state_dict from", ckpt)
    except Exception as e:
        print("Could not load state_dict directly:", e)
        try:
            # try loading as a full model object
            model = torch.load(ckpt, map_location=device)
            print("Loaded full model object from", ckpt)
        except Exception as e2:
            print("Second load attempt failed:", e2)
else:
    print(f"No checkpoint found at '{ckpt}' in working dir. If you want predictions, upload the file now.")

# 8. Set model to eval mode
model.eval()

import torch.nn as nn

class HybridModel(nn.Module):
    def __init__(self, behavior_dim):
        super(HybridModel, self).__init__()
        self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.behavior_branch = nn.Sequential(
            nn.Linear(behavior_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 16)
        )
        self.classifier = nn.Linear(768 + 16, 1)

    def forward(self, input_ids, attention_mask, behavior_features):
        bert_output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = self.dropout(bert_output.last_hidden_state[:, 0, :])
        behavior_output = self.behavior_branch(behavior_features)
        combined = torch.cat((cls_output, behavior_output), dim=1)
        logits = self.classifier(combined)
        return logits

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridModel(behavior_dim=behavior_tensor.shape[1]).to(device)
print("Model instantiated on device:", device)

from torch.optim import AdamW
import torch

criterion = nn.BCEWithLogitsLoss()
optimizer = AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)

best_val_acc = 0.0

for epoch in range(1):
    model.train()
    total_loss = 0

    for batch in train_loader:
        ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
        optimizer.zero_grad()
        outputs = model(ids, masks, behaviors).squeeze()
        loss = criterion(outputs, labels_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} - Training Loss: {avg_train_loss:.4f}")

    # Validation
    model.eval()
    preds, true_labels = [], []

    with torch.no_grad():
        for batch in val_loader:
            ids, masks, behaviors, labels_batch = [x.to(device) for x in batch]
            outputs = model(ids, masks, behaviors).squeeze()
            preds.extend(torch.round(torch.sigmoid(outputs)).cpu().numpy())
            true_labels.extend(labels_batch.cpu().numpy())

    from sklearn.metrics import classification_report, accuracy_score
    val_acc = accuracy_score(true_labels, preds)
    print("\n Validation Accuracy Report:\n")
    print(classification_report(true_labels, preds, digits=4))

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_hybrid_model.pt")
        print("Best model saved!\n")

print("Training complete. Best val acc:", best_val_acc)

import time
import torch

# Function to predict one tweet
def predict_one(tweet_text, beh_vector, threshold=0.6):
    enc = tokenizer([tweet_text], padding='max_length', truncation=True, max_length=128, return_tensors='pt')
    input_ids = enc['input_ids'].to(device)
    attention_mask = enc['attention_mask'].to(device)
    beh_scaled = scaler.transform([beh_vector])
    beh_tensor = torch.tensor(beh_scaled, dtype=torch.float32).to(device)

    with torch.no_grad():
        logits = model(input_ids, attention_mask, beh_tensor).squeeze()
        prob = torch.sigmoid(logits).item()
        pred = 1 if prob > threshold else 0

    return prob, pred

# Demo examples
examples = [
    ("Verify your account immediately at http://bit.ly/fake", [10,1,0,0,0,1,2]),   # phishing
    ("Had a great day today with friends #weekend", [8,0,1,0,1,520,400]),           # non-phishing
    ("You won a prize! Claim now: http://tinyurl.com/free-gift", [12,1,0,0,0,5,10]),# phishing
    ("Lunch at the new cafe was amazing!", [9,0,0,0,0,300,350]),                   # non-phishing
    ("Security alert: Reset password immediately: http://verify-twitter.net", [11,1,0,0,0,2,5]) # phishing
]

# Run demo
for text, beh in examples:
    t0 = time.time()
    prob, pred = predict_one(text, beh)
    t1 = time.time()
    print(f"Text: {text}")
    print(f"Prob(phish)={prob:.4f}, Pred={pred}, latency={(t1-t0)*1000:.1f} ms\n")